### ISSUE TITLE
"FPWSE0005E" - "Invalid value was provided. Check the 'target' parameter value."

### ISSUE THREAD

**Issue by JacopoMangiavacchi** [ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-swift#14]
Hi there,

I'm always getting this error message when sending a Push notification through this API on both Linux and macOS.

I saw that removing the target/platforms array resolve the problem, even if I agree this is in line with the swagger api documentation.

i.e. Wrong payload
{
	"target" : {
		"platforms" : ["A"],
		"deviceIds" : [ ... ]
	},
	"settings" : {
		"apns" : {
			"sound" : "default",
			"badge" : 1,
			"type" : "DEFAULT",
			"payload" : {
				"messageId" : "messageId"
			}
		}
	},
	"message" : {
		"alert" : "Test Push Swift Server"
	}
}

i.e. Correct payload
{
	"target" : {
		"deviceIds" : [ ... ]
	},
	"settings" : {
		"apns" : {
			"sound" : "default",
			"badge" : 1,
			"type" : "DEFAULT",
			"payload" : {
				"messageId" : "messageId"
			}
		}
	},
	"message" : {
		"alert" : "Test Push Swift Server"
	}
}

Here is the swift code I'm using:

import BluemixPushNotifications

let pushNotifications: PushNotifications = PushNotifications(bluemixRegion: "ng.bluemix.net", bluemixAppGuid: ..., bluemixAppSecret: ...)

let target = Notification.Target(deviceIds: [...], userIds: nil, platforms: [TargetPlatform.Apple], tagNames: nil)
let notificationMessage = Notification.Message(alert: "Test Push Swift Server", url: nil)

let apnsSetting = Notification.Settings.Apns(badge: 1, category: nil, iosActionKey: nil, sound: "default", type: ApnsType.DEFAULT, payload: ["messageId" : "messageId"])

let notification = Notification(message: notificationMessage, target: target, apnsSettings: apnsSetting, gcmSettings: nil)

pushNotifications.send(notification: notification) { (errore) in
    if errore != nil {
        print("Failed to send push notification. Error: \(errore)")
    }
}

Btw the same code was working with previous version of this package.

Thanks,
Jacopo

PS Could you please also update the package dependencies tree to Kitura 1.3 ?

**Comment by meyumeapps** [comment]
Yes, getting the same error.
Removing the platform type fixed it.
Would be nice to not get the error if we specify the type.

**Comment by ManavIBM** [comment]
Hi,

Its not a issue with server SDK, we should give either platforms or devciceIds or userIDS or
tagNames, that we will include in our documentation in the next release.

And it make sense as if you already providing a deviceId then providing platform does not make sense, just think the other way round.

Thanks
