### ISSUE TITLE
won't authenticate

### ISSUE THREAD

**Issue by mrdavemorgan** [ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-swift#41]
I don't think this library is authenticating properly. I get a 401 each time I try to send a message, even though I have used the correct appGuid and clientSecret from the service credentials. How can I test this?

**Comment by AnanthaKrish** [comment]
@mrdavemorgan Hi, Please use the latest Swift SDK. Which have init method with apikey. https://github.com/ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-swift#initialize-with-apikey
