### ISSUE TITLE
sendBulk fails due to misformatted JSON

### ISSUE THREAD

**Issue by mrdavemorgan** [ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-swift#44]
HTTP call is returning an error due to misformatted JSON string.  Contains a few "]" characters without matching "[" characters.

**Comment by mrdavemorgan** [comment]
pull request #45

**Comment by AnanthaKrish** [comment]
@mrdavemorgan Thanks For pointing out the issue . I have merged your PR.
