### ISSUE TITLE
Fatal Error on Linux during getAuthToken

### ISSUE THREAD

**Issue by kenlaws** [ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-swift#48]
```
notifications = PushNotifications(...
notifications.getAuthToken { ...
```
Somewhere in the getAuthToken call, this happens:
`Fatal error: value(forKey:) is not supported on this platform: file Foundation/NSDictionary.swift, line 36`
This does not happen on the Mac, only on Linux (and thus when deploying to the cloud.)

Do I need to include something I'm not including?

**Comment by AnanthaKrish** [comment]
@kenlaws Hi, You can use the latest version `1.0.0`. I have fixed the issue. 👍

**Comment by kenlaws** [comment]
Confirmed! Thanks!
